#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5ECharacterBuilder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CharacterBuilder")]
	public partial class CharacterBuilderDB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArmor(Armor instance);
    partial void UpdateArmor(Armor instance);
    partial void DeleteArmor(Armor instance);
    #endregion
		
		public CharacterBuilderDB() : 
				base(global::_5ECharacterBuilder.Properties.Settings.Default.CharacterBuilderConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CharacterBuilderDB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CharacterBuilderDB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CharacterBuilderDB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CharacterBuilderDB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Armor> Armors
		{
			get
			{
				return this.GetTable<Armor>();
			}
		}
		
		public System.Data.Linq.Table<Feature> Features
		{
			get
			{
				return this.GetTable<Feature>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Armors")]
	public partial class Armor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private int _Cost;
		
		private int _BaseArmor;
		
		private int _MaxDexBonus;
		
		private int _RequiredStrength;
		
		private bool _StealthDisadvantage;
		
		private int _Weight;
		
		private string _Category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCostChanging(int value);
    partial void OnCostChanged();
    partial void OnBaseArmorChanging(int value);
    partial void OnBaseArmorChanged();
    partial void OnMaxDexBonusChanging(int value);
    partial void OnMaxDexBonusChanged();
    partial void OnRequiredStrengthChanging(int value);
    partial void OnRequiredStrengthChanged();
    partial void OnStealthDisadvantageChanging(bool value);
    partial void OnStealthDisadvantageChanged();
    partial void OnWeightChanging(int value);
    partial void OnWeightChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    #endregion
		
		public Armor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Int NOT NULL")]
		public int Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseArmor", DbType="Int NOT NULL")]
		public int BaseArmor
		{
			get
			{
				return this._BaseArmor;
			}
			set
			{
				if ((this._BaseArmor != value))
				{
					this.OnBaseArmorChanging(value);
					this.SendPropertyChanging();
					this._BaseArmor = value;
					this.SendPropertyChanged("BaseArmor");
					this.OnBaseArmorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDexBonus", DbType="Int NOT NULL")]
		public int MaxDexBonus
		{
			get
			{
				return this._MaxDexBonus;
			}
			set
			{
				if ((this._MaxDexBonus != value))
				{
					this.OnMaxDexBonusChanging(value);
					this.SendPropertyChanging();
					this._MaxDexBonus = value;
					this.SendPropertyChanged("MaxDexBonus");
					this.OnMaxDexBonusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiredStrength", DbType="Int NOT NULL")]
		public int RequiredStrength
		{
			get
			{
				return this._RequiredStrength;
			}
			set
			{
				if ((this._RequiredStrength != value))
				{
					this.OnRequiredStrengthChanging(value);
					this.SendPropertyChanging();
					this._RequiredStrength = value;
					this.SendPropertyChanged("RequiredStrength");
					this.OnRequiredStrengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StealthDisadvantage", DbType="Bit NOT NULL")]
		public bool StealthDisadvantage
		{
			get
			{
				return this._StealthDisadvantage;
			}
			set
			{
				if ((this._StealthDisadvantage != value))
				{
					this.OnStealthDisadvantageChanging(value);
					this.SendPropertyChanging();
					this._StealthDisadvantage = value;
					this.SendPropertyChanged("StealthDisadvantage");
					this.OnStealthDisadvantageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int NOT NULL")]
		public int Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Features")]
	public partial class Feature
	{
		
		private string _Name;
		
		private string _Description;
		
		public Feature()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
